# version: '3.8'
# services:
#   postgres:
#     image: postgres:15
#     restart: always
#     environment:
#       POSTGRES_DB: mp_keywords
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ['CMD-SHELL', 'pg_isready -U postgres']
#       interval: 30s
#       timeout: 10s
#       retries: 3
# volumes:
# postgres_data:

services:
  postgres:
    # ⛔️ DON'T USE: image: postgres:15
    # ✅ DO USE:
    image: pgvector/pgvector:pg16 # Use a tag that matches your PG version (e.g., pg15, pg16)
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: x1-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
